# Generated by Django 4.2.6 on 2023-10-26 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('qtd_paginas', models.IntegerField()),
                ('qtd_exemplares', models.IntegerField()),
                ('capa', models.ImageField(upload_to='')),
                ('autor', models.CharField(max_length=255)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_.generos')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
    ]
