# Generated by Django 4.2.6 on 2023-11-30 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biblioteca_', '0002_livros_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='emprestado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livros',
            name='emprestado_para',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livros_pegos_emprestado', to=settings.AUTH_USER_MODEL, verbose_name='Emprestado para'),
        ),
        migrations.AlterField(
            model_name='livros',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros_emprestados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
