# Generated by Django 4.2.6 on 2023-11-30 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biblioteca_', '0003_livros_emprestado_livros_emprestado_para_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivroAlugado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_.livros')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Livro Alugado',
                'verbose_name_plural': 'Livros Alugados',
            },
        ),
    ]
