# Generated by Django 4.2.6 on 2023-12-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_', '0004_livroalugado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='qtd_exemplares',
            field=models.IntegerField(default=1),
        ),
    ]
